version: '3'
services:
  vault:
    image: "vault"
    hostname: "vault"
    environment:
      VAULT_ADDR: http://127.0.0.1:8200
    ports:
      - "8200:8200"
    cap_add:
    - IPC_LOCK
  sshd:
    build:
      context: ./sshd
    links:
    - vault
    ports:
      - "2222:22"
      

