version: '3'
services:
  vault:
    build:
      context: ./vault
    ports:
      - "8200:8200"
    cap_add:
    - IPC_LOCK
  sshd:
    build:
      context: ./sshd
    links:
    - vault
    ports:
      - "2222:22"
    volumes:
      - ./sshd/ca:/ca
      

